config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :comments, :only => [:create]
  resources :charges
  resource :session, :only => [:create, :destroy]
  
  get "/auth/:provider/callback" => "sessions#create"
  get "/signout" => "sessions#destroy", :as => :signout
  
  get 'tags/:tag', to: 'posts#index', as: "tag"

  root'home#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, :dependent => :destroy
  has_many :taggings, :dependent => :destroy
  has_many :tags, :through => :taggings
  accepts_nested_attributes_for :comments
  belongs_to :user
  mount_uploader :avatar, AvatarUploader

  def self.tagged_with(name)
  Tag.find_by_name!(name).posts
  end

   def all_tags=(names)
    self.tags = names.split(",").map do |name|
      Tag.where(name: name.strip).first_or_create!
    end
  end
 
  def all_tags
    self.tags.map(&:name).join(", ")
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts , :through => :taggings
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :post
  belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts

  def self.authorize_with(auth)
    where(provider: auth["provider"], uid: auth["uid"]).first_or_create.tap do |u|
      u.name         = auth.info.name
      u.email        = auth.info.email
      u.nickname     = auth.info.nickname
      u.access_token = auth.credentials.token
      u.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def require_authenticated_user
    unless current_user
      redirect_to :root, :notice => "Authentication Required."
    end
  end

  protected

  def current_user
    @current_user ||= User.where(id: session[:user_id]).first 
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to charges_path
  end

  def index
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @post.comments.create(comment_params)
    redirect_to post_path(@post), notice: "comment added"
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :email, :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @recent_posts = Post.order('created_at DESC').limit(3)
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :destroy]

  before_action :require_authenticated_user, :except => [:index, :show]

  def index
  if params[:tag]
    @posts = Post.tagged_with(params[:tag])
  else
    @posts = Post.all
  end
end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.create(post_params)

    if @post.save
      redirect_to @post, notice: 'Post was successfuly created'
    else 
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to@post, notice: 'Review was successfuly updated'
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to root_path, notice: 'Post was deleted'
  end

  def show
    @post=Post.find(params[:id])
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:user_id, :title, :body, :avatar, :all_tags)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
   def create
    user = User.authorize_with(request.env["omniauth.auth"])
    if user
      session[:user_id] = user.id
      redirect_to root_path 
    else
      redirect_to root_path, :notice => "Fail."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, :notice => "Signed out!"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/create_users_helper.rb
module CreateUsersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def tag_links(tags)
    tags.split(",").map{|tag| link_to tag.strip, tag_path(tag.strip) }.join(", ") 
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/home/index.html.erb
<h1>Boring Yawn..</h1>

<h2>This blog is about really boring things.</h2>

<ul>
  <% @recent_posts.each do |post| %>
    <li>
      <%= link_to image_tag(post.avatar.thumb.url, :size => '32x32') %>
      <%= link_to "#{post.title}", post_path(post) %>
      <%= truncate post.body, length: 90, separator: ' ' %>
      <% if current_user %>
        <%= link_to 'edit', edit_post_path(post) %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/home/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th><%= @post.title %></th>
    </tr>
  </thead>
  <tfoot>
    <tr>
      <th>Tags</th>
    </tr>
    <tr>
      <td><%= @post.all_tags %></td>
    </tr>
  </tfoot>
  <tbody>
    <tr>
      <td>
        <%= link_to image_tag(@post.avatar.url, :size => '408x544') %>
      </td>
    </tr>
    <tr>
      <td>
        <%= @post.body %>
      </td>
    </tr>
    <tr></tr>
  </tbody>
</table>

<ul>
  <% @post.comments.each do |comment| %>
    <li>
      <p><%= comment.body %></p>
      <p class="author">by <%= comment.author %> on <%= comment.created_at.to_s(:short) %></p>
    </li>
  <% end %>
</ul>

<%= form_for(@post.comments.new) do |f| %>
  <%= hidden_field_tag :post_id, @post.id %>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

<% if current_user %>
  <%= link_to 'edit', edit_post_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="a really boring blog">
  <meta name="author" content="Joshua Wykell">
  <title>Boring Blog</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Boring Blog", "/", class: "navbar-brand" %>
      </div>
       <div id="navbar" class="navbar-collapse collapse">
        <% unless current_user %>
        <form>
          <button type="submit" class="btn btn-success"><%= link_to"Sign in with Github", "/auth/github" %></button>
        </form>
        <% else %>
          <form action="<%= new_post_path %>" method="GET" class="navbar-form navbar-right">
            <button type="submit" class="btn btn-default">New Post</button>
          </form>

          <form>
            <button type="submit" class="btn btn-default"><%= link_to "Sign out", signout_path%> </button>
          </form>
        <% end %>
        </div>
      </div>
    </div>
  </nav>

  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>
  </div>

  <%= yield %>
    
  <div class="footer">
    <div class="footer_left">
      <p class="muted credit"> a jlistens app </p>
    </div>
    <div class="footer_right blog_form">
      <%= form_tag charges_path do %>
        <article>
          <p>Make a donation to support the blog</p>
          <label class="amount">
            <span>Amount: $5.00</span>
          </label>
        </article>
    </div>
    <div class="footer_right blog_button">
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="A month's subscription"
                data-amount="500"></script>
      <% end %>
    </div>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<!-- add image tag for image -->
<%= form_for(@post, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @post.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h4>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :title, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :avatar, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.file_field :avatar, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :body, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :body, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :tag, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :all_tags, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="page-header">
  
  <h1>Editing Post</h1>
</div>

<%= render 'form' %>

app/views/posts/index.html.erb
<h2>An index of similarly tagged <%= @tag.try(:name) %></h2>

<ul>
  <% @posts.each do |post| %>
    <li>
      <%= link_to image_tag(post.avatar.thumb.url, :size => '32x32') %>
      <%= link_to "#{post.title}", post_path(post) %>
      <%= truncate post.body, length: 90, separator: ' ' %>
      <% if current_user %>
        <%= link_to 'edit', edit_post_path(post) %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/posts/new.html.erb
<div class="page-header">
  
  <h1>New Post</h1>
</div>

<%= render 'form' %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th><h3><%= @post.title %></h3></th>
    </tr>
  </thead>
    <tr>
      <td>
        <%= link_to image_tag(@post.avatar.url, :size => '408x544') %>
      </td>
    </tr>
    <tr>
      <td><%= @post.body %></td>
    </tr>
    <tr> </tr>
    <tr> </tr>
    <tr> </tr>
    <tr> </tr>
  </tbody>
</table>

<h5>Tags:</h5><p><%=raw tag_links(@post.all_tags)%></p>

<h4>Comments:</h4>

<ul>
  <% @post.comments.each do |comment| %>
    <li>
      <p><%= comment.body %></p>
      <p class="author">by <%= comment.author %> on <%= comment.created_at.to_s(:short) %></p>
    </li>
  <% end %>
</ul>

<h5>add a comment</h5>

<%= form_for(@post.comments.new, :url => comments_path(@post)) do |f| %>
  <%= hidden_field_tag :post_id, @post.id %>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<% if current_user %>
  <%= link_to 'edit', edit_post_path %>
  <%= link_to 'delete', post_path, method: :delete, data: { confirm: 'Are you sure?' }  %>
<% end %>